### PR TITLE
Flecsale mpi

### PR DESCRIPTION
**Pull request by ipdemes**

### CODE REVIEW

**Comment by charest** [comment]
Works for the 2d case!  Running hydro_3d, with this mesh ([cube_3k_tet.zip](https://github.com/laristra/flecsale/files/1250519/cube_3k_tet.zip)), I get :

hydro_3d: /home/charest/code/flecsale/flecsi/flecsi/topology/common/array_buffer.h:187: void flecsi::topology::array_buffer__<T>::resize(size_t) [with T = flecsi::utils::id_<20, 40, 4, 60>; size_t = long unsigned int]: Assertion `n <= capacity_' failed.

**Comment by ollielo** [comment]
@charest ,

The reason of the assertion failure is that I haven't figure how to correctly set the total number of indices for connectivities [number of indices](https://github.com/laristra/flecsi/blob/17b00b17141d524797fd43a15d69de845aa35d96/flecsi/execution/mpi/task_prolog.h#L212) when allocating memory. I don't think it is right to allocate `number_of_from_entities * number_of_to_entities` of elements like what Legion backend does.

**Comment by ollielo** [comment]
@charest , @nickm319 

Maybe `context.adjacency_info.color_sizes` is all I need for the number of indices. Is it?

**Comment by ollielo** [comment]
@charest ,

[flecsi/master](https://github.com/laristra/flecsi/commit/bf1a53437462bda888ff29d697154bd97d2c8aa5) should have corrected this bug.

**Comment by charest** [comment]
@ollielo Works now.  Thanks!

**Comment by ollielo** [comment]
@charest 

Can you update the flecsi submodule on the flegion branch?

Do you want to make a 2.0-beta release?

**Comment by charest** [comment]
I updated the feature/flegion branch to reflect the changes.  If you follow the instructions, checking out will get you these changes.

**Pull request merged**
